# constants.py
# reference pour ces constantes : https://www.ecologie.gouv.fr/sites/default/files/documents/Comite_scientfique_observation_loyers_annexe_abreviations_noms_voie.pdf
TYPE_VOIE_ABBR = {
    "LIEU-DIT": "LDT",
    "AERODROME": "AERD",
    "LOTISSEMENT": "LOT",
    "AEROGARE": "AERG",
    "MAIL": "MAIL",
    "ALLEE": "ALL",
    "MAISON": "MAIS",
    "AUTOROUTE": "A",
    "MARCHE": "MARC",
    "AVENUE": "AV",
    "MARCHE": "MCH",
    "BALCON": "BALC",
    "MARE": "MARE",
    "BARRAGE": "BRG",
    "METRO": "METR",
    "BARRIERE": "BARR",
    "MONT": "MONT",
    "BASSIN": "BASS",
    "MONTEE": "MNT",
    "BOIS": "BOIS",
    "PALAIS": "PAL",
    "BOULEVARD": "BD",
    "PARC": "PARC",
    "BUTTE": "BUTT",
    "PARKING": "PKG",
    "CARREFOUR": "CARR",
    "PARVIS": "PARV",
    "CASERNE": "CAS",
    "PASSAGE": "PASS",
    "CENTRE COMMERCIAL": "CCAL",
    "PAVILLON": "PAV",
    "CHALET": "CHAL",
    "PELOUSE": "PEL",
    "CHAMP": "CHP",
    "PETITE RUE": "PTR",
    "CHATEAU": "CHAT",
    "PIECE": "PIEC",
    "CHAUSSEE": "CHAU",
    "PLACE": "PL",
    "CHEMIN": "CHEM",
    "PLAINE": "PLAI",
    "CHEMIN DEPARTEMENTAL": "CD",
    "POINT KILOMETRIQUE": "PK",
    "CITE": "CITE",
    "POINTE": "PNTE",
    "CLAIRIERE": "CLR",
    "PONT": "PONT",
    "CLIMAT": "CLIM",
    "PORT": "PORT",
    "CLOS": "CLOS",
    "PORTE": "PRTE",
    "CONTOUR": "CONT",
    "PRAIRIE": "PRAI",
    "COTE": "COTE",
    "PRE": "PRE",
    "COTTAGE": "COTT",
    "PROMENADE": "PROM",
    "COUR": "CR",
    "QUAI": "QUAI",
    "COURS": "CRS",
    "QUARTIER": "QUAR",
    "DOMAINE": "DOM",
    "RAMPE": "RPE",
    "ECLUSE": "ECL",
    "RER": "RER",
    "ESCALIER": "ESC",
    "RESIDENCE": "RES",
    "ESPLANADE": "ESP",
    "ROND-POINT": "RDPT",
    "ETANG": "ETG",
    "ROUTE": "RTE",
    "FAUBOURG": "FBG",
    "ROUTE DEPARTEMENTALE": "RD",
    "FERME": "FERM",
    "ROUTE NATIONALE": "RN"
}
